const SVG={search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6"></circle><path d="m16 16 4 4"></path></svg>',bag:'<svg viewBox="0 0 24 24"><path d="M5 8h14l-1 12H6L5 8Z"></path><path d="M9 8V6a3 3 0 0 1 6 0v2"></path></svg>',menu:'<svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"></path></svg>',pin:'<svg viewBox="0 0 24 24"><path d="M12 21s6-5.3 6-11a6 6 0 1 0-12 0c0 5.7 6 11 6 11Z"></path><circle cx="12" cy="10" r="2"></circle></svg>',chevron:'<svg viewBox="0 0 24 24"><path d="m7 9 5 5 5-5"></path></svg>',rotate:'<svg viewBox="0 0 24 24"><path d="M20 11a8 8 0 1 0-2.3 5.7"></path><path d="M20 4v7h-7"></path></svg>',trash:'<svg viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"></path></svg>'};document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=SVG[el.dataset.icon]||'');
const state={city:'',color:'Ivory',size:'M',patch:false,x:50,y:47,scale:.72,rotation:0,bag:0};
const cities=['Kolkata, India','Delhi, India','Mumbai, India','Bengaluru, India','Chennai, India','Hyderabad, India','Pune, India','Jaipur, India','Ahmedabad, India','Lucknow, India','New York, USA','Los Angeles, USA','Chicago, USA','San Francisco, USA','London, UK','Paris, France','Tokyo, Japan','Dubai, UAE','Singapore','Toronto, Canada'];
const colors=[['Ivory','#f1eadc'],['White','#f6f6f2'],['Black','#1c1c1b'],['Navy','#263750'],['Charcoal','#53514f'],['Heather Grey','#aaa9a5'],['Olive','#70785b'],['Sage','#a3b199'],['Maroon','#7e2d2c'],['Burgundy','#701f2b'],['Chocolate','#5c3b2b'],['Sand','#d8c9b2'],['Taupe','#b2a391'],['Dusty Blue','#97acbd'],['Dusty Pink','#d5abae']];
const shirtFiles=Object.fromEntries(colors.map(([n])=>[n,'shirt-'+n.toLowerCase().replaceAll(' ','-')+'.png']));const sizes=['XS','S','M','L','XL','XXL'];const screens=[...document.querySelectorAll('.screen')];
function progress(step){return ['CITY','T-SHIRT','PATCHES','REVIEW','CHECKOUT'].map((n,i)=>`<div class="step ${i+1<step?'done':''} ${i+1===step?'current':''}">${String(i+1).padStart(2,'0')} ${n}</div>`).join('')}document.querySelectorAll('.progress').forEach(p=>p.innerHTML=progress(+p.dataset.step));
function go(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo(0,0);if(id==='shirt')renderShirt();if(id==='patches')renderPatch();if(id==='review')renderReview()}document.querySelectorAll('[data-go]').forEach(el=>el.onclick=e=>{e.preventDefault();go(el.dataset.go)});
const comboBtn=document.getElementById('cityComboBtn'),dropDown=document.getElementById('cityDropdown'),search=document.getElementById('citySearch'),cityList=document.getElementById('cityList'),cityContinue=document.getElementById('cityContinue'),comboLabel=document.getElementById('cityComboLabel');comboBtn.onclick=()=>{dropDown.classList.toggle('hidden');if(!dropDown.classList.contains('hidden'))search.focus()};document.addEventListener('click',e=>{if(!e.target.closest('.combo'))dropDown.classList.add('hidden')});
function renderCities(q=''){cityList.innerHTML='';cities.filter(c=>c.toLowerCase().includes(q.toLowerCase())).forEach(c=>{const b=document.createElement('button');b.innerHTML=`${SVG.pin}<span>${c}</span>`;b.className=state.city===c?'selected':'';b.onclick=()=>{state.city=c;comboLabel.textContent=c;cityContinue.disabled=false;dropDown.classList.add('hidden');renderCities()};cityList.appendChild(b)})}renderCities();search.oninput=()=>renderCities(search.value);cityContinue.onclick=()=>state.city&&go('shirt');
function syncShirtImages(){const src=shirtFiles[state.color]||shirtFiles.Ivory;document.getElementById('shirtPreview').src=src;document.getElementById('patchShirt').src=src;document.getElementById('reviewShirt').src=src}
function renderShirt(){if(!state.city)state.city='Kolkata, India';selectedCityLabel.textContent=state.city;selectedCityBtn.onclick=()=>go('city');const sw=document.getElementById('swatches');sw.innerHTML='';colors.forEach(([n,c])=>{const b=document.createElement('button');b.className='swatch '+(state.color===n?'active':'');b.innerHTML=`<span style="background:${c}"></span><small>${n}</small>`;b.onclick=()=>{state.color=n;syncShirtImages();renderShirt()};sw.appendChild(b)});const sz=document.getElementById('sizes');sz.innerHTML='';sizes.forEach(s=>{const b=document.createElement('button');b.className='size '+(state.size===s?'active':'');b.textContent=s;b.onclick=()=>{state.size=s;renderShirt()};sz.appendChild(b)});syncShirtImages()}
renderShirt();
const modal=document.getElementById('sizeModal');function openSize(){modal.classList.remove('hidden')}function closeSize(){modal.classList.add('hidden')}openSize.onclick=null;document.getElementById('openSize').onclick=openSize;document.getElementById('openSize2').onclick=openSize;document.getElementById('closeSize').onclick=closeSize;modal.onclick=e=>{if(e.target===modal)closeSize()};
const patchTile=document.getElementById('patchTile'),placed=document.getElementById('placedPatch'),drop=document.getElementById('dropZone'),tools=document.getElementById('patchControls');
function addPatch(x=50,y=47){state.patch=true;state.x=Math.max(23,Math.min(77,x));state.y=Math.max(20,Math.min(80,y));renderPatch()}function removePatch(){state.patch=false;renderPatch()}patchTile.onclick=()=>state.patch?removePatch():addPatch();patchTile.ondragstart=e=>e.dataTransfer.setData('text/plain','patch');drop.ondragover=e=>e.preventDefault();drop.ondrop=e=>{e.preventDefault();const r=drop.getBoundingClientRect();addPatch((e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100)};removePatchBtn=document.getElementById('removePatch');removePatchBtn.onclick=removePatch;document.getElementById('bigger').onclick=()=>{state.scale=Math.min(2.2,state.scale+.12);renderPatch()};document.getElementById('smaller').onclick=()=>{state.scale=Math.max(.22,state.scale-.12);renderPatch()};document.getElementById('rotatePatch').onclick=()=>{state.rotation=(state.rotation+15)%360;renderPatch()};
let dragging=false;placed.onpointerdown=e=>{dragging=true;placed.setPointerCapture(e.pointerId)};placed.onpointermove=e=>{if(!dragging)return;const r=drop.getBoundingClientRect();state.x=Math.max(23,Math.min(77,(e.clientX-r.left)/r.width*100));state.y=Math.max(20,Math.min(80,(e.clientY-r.top)/r.height*100));renderPatch()};placed.onpointerup=()=>dragging=false;placed.onpointercancel=()=>dragging=false;
function renderPatch(){patchCityLabel.textContent=state.city||'Kolkata, India';patchCity.onclick=()=>go('city');mixCityBtn.onclick=()=>go('city');patchTile.classList.toggle('selected',state.patch);placed.classList.toggle('hidden',!state.patch);tools.classList.toggle('hidden',!state.patch);selectedCount.textContent=(state.patch?'1':'0')+' of 6 selected.';placed.style.left=state.x+'%';placed.style.top=state.y+'%';placed.style.width=(110*state.scale)+'px';placed.style.setProperty('--rot',state.rotation+'deg');tools.style.left=state.x+'%';tools.style.top=Math.min(90,state.y+12)+'%';syncShirtImages()}renderPatch();
function renderReview(){reviewCity.textContent=state.city||'Kolkata, India';reviewShirtMeta.textContent=`${state.color} | Size ${state.size}`;reviewCount.textContent=state.patch?1:0;reviewPatch.classList.toggle('hidden',!state.patch);reviewPatch.style.left=state.x+'%';reviewPatch.style.top=state.y+'%';reviewPatch.style.width=(110*state.scale)+'px';reviewPatch.style.setProperty('--rot',state.rotation+'deg');reviewPatchList.innerHTML=state.patch?'<div class="mini"><img src="patch-chai-bhar.png"></div>':'';patchPrice.textContent=state.patch?'₹ 250':'₹ 0';totalPrice.textContent=state.patch?'₹ 1,748':'₹ 1,498';syncShirtImages()}addBag.onclick=()=>{state.bag++;bagCount.textContent=state.bag};
