const screens=[...document.querySelectorAll('.screen')];
const state={city:'',color:'Ivory',size:'M',patch:false,patchX:50,patchY:45,patchScale:1,bag:0};
const cities=['Kolkata, India','Delhi, India','Mumbai, India','Bengaluru, India','Chennai, India','Hyderabad, India','Pune, India','Jaipur, India','Ahmedabad, India','Lucknow, India','New York, USA','Los Angeles, USA','Chicago, USA','San Francisco, USA','London, UK','Paris, France','Tokyo, Japan','Dubai, UAE','Singapore','Toronto, Canada'];
const colors=[['Ivory','#f2ebdc'],['Black','#151515'],['Navy','#21344e'],['Maroon','#7f2929'],['Olive','#677451']];
const sizes=['XS','S','M','L','XL','XXL'];
function stepper(step){return ['CITY','T-SHIRT','PATCHES','REVIEW','CHECKOUT'].map((x,i)=>`<div class="st ${i+1<step?'done':''} ${i+1===step?'current':''}">${String(i+1).padStart(2,'0')} ${x}</div>`).join('')}
document.querySelectorAll('.stepper').forEach(el=>el.innerHTML=stepper(+el.dataset.step));
function go(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='shirt')renderShirt();if(id==='patches')renderPatchState();if(id==='review')renderReview()}
document.querySelectorAll('[data-go]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();go(el.dataset.go)}));

const cityList=document.getElementById('cityList');const citySearch=document.getElementById('citySearch');const cityContinue=document.getElementById('cityContinue');
function renderCities(filter=''){cityList.innerHTML='';cities.filter(c=>c.toLowerCase().includes(filter.toLowerCase())).forEach(c=>{const b=document.createElement('button');b.className='city-option'+(state.city===c?' selected':'');b.innerHTML=`<span>⌖</span>${c}`;b.onclick=()=>{state.city=c;citySearch.value=c;cityContinue.disabled=false;renderCities(c);};cityList.appendChild(b)});}
renderCities();citySearch.addEventListener('input',()=>renderCities(citySearch.value));cityContinue.onclick=()=>{if(state.city)go('shirt')};

const swatches=document.getElementById('swatches'),sizeWrap=document.getElementById('sizes');
function renderShirt(){if(!state.city)state.city='Kolkata, India';document.getElementById('selectedCityBtn').textContent='⌖  '+state.city+'   ⌄';swatches.innerHTML='';colors.forEach(([n,c])=>{const b=document.createElement('button');b.className='swatch'+(state.color===n?' active':'');b.title=n;b.innerHTML=`<span style="background:${c}"></span>`;b.onclick=()=>{state.color=n;renderShirt()};swatches.appendChild(b)});sizeWrap.innerHTML='';sizes.forEach(s=>{const b=document.createElement('button');b.className='size'+(state.size===s?' active':'');b.textContent=s;b.onclick=()=>{state.size=s;renderShirt()};sizeWrap.appendChild(b)});}
renderShirt();

const modal=document.getElementById('sizeModal');function openModal(){modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}document.getElementById('openSize').onclick=openModal;document.getElementById('openSize2').onclick=openModal;document.getElementById('closeSize').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});

const patchCard=document.getElementById('patchCard'),placed=document.getElementById('placedPatch'),drop=document.getElementById('dropZone'),controls=document.getElementById('patchControls');
function patchAt(x=50,y=45){state.patch=true;state.patchX=x;state.patchY=y;renderPatchState()}
patchCard.addEventListener('click',()=>state.patch?removePatch():patchAt());patchCard.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain','patch')});drop.addEventListener('dragover',e=>e.preventDefault());drop.addEventListener('drop',e=>{e.preventDefault();const r=drop.getBoundingClientRect();patchAt(((e.clientX-r.left)/r.width)*100,((e.clientY-r.top)/r.height)*100)});
function renderPatchState(){document.getElementById('patchCity').textContent='⌖  '+(state.city||'Kolkata, India')+' ⌄';patchCard.classList.toggle('selected',state.patch);placed.classList.toggle('hidden',!state.patch);controls.classList.toggle('hidden',!state.patch);document.getElementById('selectedCount').textContent=(state.patch?'1':'0')+' of 6 selected.';placed.style.left=state.patchX+'%';placed.style.top=state.patchY+'%';placed.style.width=(88*state.patchScale)+'px';controls.style.left=state.patchX+'%';controls.style.top=Math.min(88,state.patchY+17)+'%'}
function removePatch(){state.patch=false;renderPatchState()}document.getElementById('removePatch').onclick=removePatch;document.getElementById('bigger').onclick=()=>{state.patchScale=Math.min(1.7,state.patchScale+.12);renderPatchState()};document.getElementById('smaller').onclick=()=>{state.patchScale=Math.max(.55,state.patchScale-.12);renderPatchState()};
let dragging=false;let pointerId=null;placed.addEventListener('pointerdown',e=>{dragging=true;pointerId=e.pointerId;placed.setPointerCapture(pointerId)});placed.addEventListener('pointermove',e=>{if(!dragging)return;const r=drop.getBoundingClientRect();state.patchX=Math.max(15,Math.min(85,((e.clientX-r.left)/r.width)*100));state.patchY=Math.max(15,Math.min(84,((e.clientY-r.top)/r.height)*100));renderPatchState()});placed.addEventListener('pointerup',()=>dragging=false);

function renderReview(){document.getElementById('reviewCity').textContent=state.city||'Kolkata, India';document.getElementById('reviewShirtMeta').textContent=`${state.color}  |  Size ${state.size}`;document.getElementById('reviewCount').textContent=state.patch?1:0;document.getElementById('reviewPatch').classList.toggle('hidden',!state.patch);const list=document.getElementById('reviewPatchList');list.innerHTML=state.patch?'<div class="mini-patch"><img src="patch-chai-bhar.png" alt="Chai Bhar"></div>':'';document.getElementById('patchPrice').textContent=state.patch?'₹ 250':'₹ 0';document.getElementById('totalPrice').textContent=state.patch?'₹ 1,748':'₹ 1,498';const rp=document.getElementById('reviewPatch');rp.style.left=state.patchX+'%';rp.style.top=state.patchY+'%';rp.style.width=(88*state.patchScale)+'px';}

document.getElementById('addBag').onclick=()=>{state.bag++;document.getElementById('bagCount').textContent=state.bag;document.getElementById('addBag').textContent='Added to Bag ✓';setTimeout(()=>document.getElementById('addBag').textContent='Add to Bag →',1400)};
renderPatchState();
