const state={city:'',color:'Ivory',size:'M',patch:false,x:50,y:48,scale:1,bag:0};
const cities=['Kolkata, India','Delhi, India','Mumbai, India','Bengaluru, India','Chennai, India','Hyderabad, India','Pune, India','Jaipur, India','Ahmedabad, India','Lucknow, India','New York, USA','Los Angeles, USA','Chicago, USA','San Francisco, USA','London, UK','Paris, France','Tokyo, Japan','Dubai, UAE','Singapore','Toronto, Canada'];
const colors=[['Ivory','#f1eadc'],['Black','#151515'],['Navy','#263750'],['Maroon','#7e2d2c'],['Olive','#70785b']];
const sizes=['XS','S','M','L','XL','XXL'];
const screens=[...document.querySelectorAll('.screen')];
function progress(step){return ['CITY','T-SHIRT','PATCHES','REVIEW','CHECKOUT'].map((n,i)=>`<div class="step ${i+1<step?'done':''} ${i+1===step?'current':''}">${String(i+1).padStart(2,'0')} ${n}</div>`).join('')}
document.querySelectorAll('.progress').forEach(p=>p.innerHTML=progress(+p.dataset.step));
function go(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo(0,0);if(id==='shirt')renderShirt();if(id==='patches')renderPatch();if(id==='review')renderReview()}
document.querySelectorAll('[data-go]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();go(el.dataset.go)}));
const comboBtn=document.getElementById('cityComboBtn'),dropDown=document.getElementById('cityDropdown'),search=document.getElementById('citySearch'),cityList=document.getElementById('cityList'),cityContinue=document.getElementById('cityContinue'),comboLabel=document.getElementById('cityComboLabel');
comboBtn.onclick=()=>{dropDown.classList.toggle('hidden');if(!dropDown.classList.contains('hidden'))search.focus()};
document.addEventListener('click',e=>{if(!e.target.closest('.combo'))dropDown.classList.add('hidden')});
function renderCities(q=''){cityList.innerHTML='';cities.filter(c=>c.toLowerCase().includes(q.toLowerCase())).forEach(c=>{const b=document.createElement('button');b.textContent='⌖  '+c;b.className=state.city===c?'selected':'';b.onclick=()=>{state.city=c;comboLabel.textContent=c;cityContinue.disabled=false;dropDown.classList.add('hidden');renderCities()};cityList.appendChild(b)})}
renderCities();search.oninput=()=>renderCities(search.value);cityContinue.onclick=()=>state.city&&go('shirt');
function renderShirt(){if(!state.city)state.city='Kolkata, India';const cityBtn=document.getElementById('selectedCityBtn');cityBtn.textContent='⌖  '+state.city+'   ⌄';cityBtn.onclick=()=>go('city');const sw=document.getElementById('swatches');sw.innerHTML='';colors.forEach(([n,c])=>{const b=document.createElement('button');b.className='swatch '+(state.color===n?'active':'');b.innerHTML=`<span style="background:${c}"></span><small>${n}</small>`;b.onclick=()=>{state.color=n;renderShirt()};sw.appendChild(b)});const sz=document.getElementById('sizes');sz.innerHTML='';sizes.forEach(s=>{const b=document.createElement('button');b.className='size '+(state.size===s?'active':'');b.textContent=s;b.onclick=()=>{state.size=s;renderShirt()};sz.appendChild(b)})}
renderShirt();
const modal=document.getElementById('sizeModal');function openSize(){modal.classList.remove('hidden')}function closeSize(){modal.classList.add('hidden')}document.getElementById('openSize').onclick=openSize;document.getElementById('openSize2').onclick=openSize;document.getElementById('closeSize').onclick=closeSize;modal.onclick=e=>{if(e.target===modal)closeSize()};
const patchTile=document.getElementById('patchTile'),placed=document.getElementById('placedPatch'),drop=document.getElementById('dropZone'),tools=document.getElementById('patchControls');
function addPatch(x=50,y=48){state.patch=true;state.x=Math.max(30,Math.min(70,x));state.y=Math.max(25,Math.min(78,y));renderPatch()}
patchTile.onclick=()=>state.patch?removePatch():addPatch();patchTile.ondragstart=e=>e.dataTransfer.setData('text/plain','patch');drop.ondragover=e=>e.preventDefault();drop.ondrop=e=>{e.preventDefault();const r=drop.getBoundingClientRect();addPatch((e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100)};
function removePatch(){state.patch=false;renderPatch()}document.getElementById('removePatch').onclick=removePatch;document.getElementById('bigger').onclick=()=>{state.scale=Math.min(1.8,state.scale+.12);renderPatch()};document.getElementById('smaller').onclick=()=>{state.scale=Math.max(.55,state.scale-.12);renderPatch()};
let dragging=false;placed.onpointerdown=e=>{dragging=true;placed.setPointerCapture(e.pointerId)};placed.onpointermove=e=>{if(!dragging)return;const r=drop.getBoundingClientRect();state.x=Math.max(30,Math.min(70,(e.clientX-r.left)/r.width*100));state.y=Math.max(25,Math.min(78,(e.clientY-r.top)/r.height*100));renderPatch()};placed.onpointerup=()=>dragging=false;
function renderPatch(){document.getElementById('patchCity').textContent='⌖  '+(state.city||'Kolkata, India')+' ⌄';patchTile.classList.toggle('selected',state.patch);placed.classList.toggle('hidden',!state.patch);tools.classList.toggle('hidden',!state.patch);const countText=(state.patch?'1':'0')+' of 6 selected.';document.getElementById('selectedCount').textContent=countText;const top=document.getElementById('selectedCountTop');if(top)top.textContent=(state.patch?'1':'0')+' / 6';placed.style.left=state.x+'%';placed.style.top=state.y+'%';placed.style.width=(92*state.scale)+'px';tools.style.left=state.x+'%';tools.style.top=Math.min(91,state.y+15)+'%'}
renderPatch();
function renderReview(){document.getElementById('reviewCity').textContent=state.city||'Kolkata, India';document.getElementById('reviewShirtMeta').textContent=`${state.color} | Size ${state.size}`;document.getElementById('reviewCount').textContent=state.patch?1:0;const rp=document.getElementById('reviewPatch');rp.classList.toggle('hidden',!state.patch);rp.style.left=state.x+'%';rp.style.top=state.y+'%';rp.style.width=(92*state.scale)+'px';document.getElementById('reviewPatchList').innerHTML=state.patch?'<div class="mini"><img src="patch-chai-bhar.png"></div>':'';document.getElementById('patchPrice').textContent=state.patch?'₹ 250':'₹ 0';document.getElementById('totalPrice').textContent=state.patch?'₹ 1,748':'₹ 1,498'}
document.getElementById('addBag').onclick=()=>{state.bag++;document.getElementById('bagCount').textContent=state.bag};
